### ISSUE TITLE
Bug multiselect

### ISSUE THREAD

**Issue by K15Lmk98** [felixarntz/wpdlib#4]
Hello,
sorry, this is an automatic translation.

Type multiselect field does not work well.

The selection of one or more terms is correct, but when I save the changes, the field becomes empty.
However, the value is saved in the database correctly.

I attach screenshots.

Mac OSX: 10.11.3
Browsers: Chrome (48.0.2564.109) Firefox (44.0.2)
WordPress 4.4.2 with the theme Twenty Sixteen
Plugin active: Options Definitely(0.6.1) only

Thanks, Claudio_

![after save](https://cloud.githubusercontent.com/assets/15044414/13142365/cdf3922a-d63c-11e5-9616-4ff092f91c32.png)
![before save](https://cloud.githubusercontent.com/assets/15044414/13142366/ce040614-d63c-11e5-9bb0-9f9cc35d2af4.png)
![plugin](https://cloud.githubusercontent.com/assets/15044414/13142367/ce0726e6-d63c-11e5-987f-4e0cd5b3f236.png)

**Comment by felixarntz** [comment]
Thanks for the report! I'll investigate and fix this as soon as possible.
